### ISSUE TITLE
Step 1 - Project Organization and File Creator fields

### ISSUE THREAD

**Issue by fecaps** [ViniciusMartinsS/nodejs#2]
- **Project Organization:**

It would be better to move the `package.json` file from `step1` folder to project root folder, and then configuring npm scripts for each step on it.

Example of `scripts` session on `package,json` file:

```json
"scripts": {
  "step1": "node step01/index.js",
  "test": "echo \"Error: no test specified\" && exit 1"
}
```

Besides that, `.eslintrc`, `.editorconfig` and `.env.dist` files could be in the project root as well. If you choose to do it, you can rename the env variables with a prefix, like `STEP1_FOLDER_NAME`, etc.

Regarding the `README` file, you can keep it in each step but without `installing` session.

- **File Creator fields:**

Why have you decided to use the `content` const as an object when you use it with array notation in `writeFileSync(content[i].path, content[i].message)` method?

**Comment by ViniciusMartinsS** [comment]
All changes requested were done.
